#!/bin/bash
#-----------------------------------------------------------
#   Autor       : ucabrera
#   Date        : 18/01/2020
#   
#   VAR_VARNAME     Local Variables
#   PHO_VARNAME     Variables that would be visibles to Pentaho
#-----------------------------------------------------------

Pi()
{
	VAR_ENVIRONMENT="PI"
	VAR_INTE_PATH="$HOME/Projects/trunk"
	VAR_DATA_PATH="$HOME/Projects/trunk"
	VAR_PDI_PATH="$HOME/localApps"
	PENTAHO_DI_JAVA_OPTIONS="-Xms256m -Xmx512m"

	PHO_DB_HOST="userver"
	PHO_DB_PORT="3306"
	PHO_DB_DBNAME="BET_DB_P"
	PHO_DB_USER="ucabrera"
	PHO_DB_PASS="ucabreraPass"
}

Dev()
{
	VAR_ENVIRONMENT="DEV"
	VAR_INTE_PATH="$HOME/Projects/DEV"
	VAR_DATA_PATH="$HOME/Projects/DEV"
	VAR_PDI_PATH="$HOME/localApps"
	PENTAHO_DI_JAVA_OPTIONS=

	PHO_DB_HOST="userver"
	PHO_DB_PORT="3306"
	PHO_DB_DBNAME="BET_DB_D"
	PHO_DB_USER="ucabrera"
	PHO_DB_PASS="ucabreraPass"
}

if [ "$HOSTNAME" = "userver" ]; then
	Pi
else
	Dev
fi

VAR_FORMAT_DATE="%d%m%Y"                                          			# General Format for dates
VAR_FORMAT_DATE_YEARMONTH="%Y%m"                                            # General Format for dates YM
VAR_FORMAT_DATEMINSEG="%d/%m/%Y %H:%M:%S"                         			# General Format for date hr:min:ss
VAR_INTEGRATION_PATH=$VAR_INTE_PATH/BET_Integration
VAR_INTEGRATION_DATA_PATH=$VAR_DATA_PATH/BET_IntegrationData
PHO_JOBS_PATH=$VAR_INTEGRATION_PATH/Jobs
PHO_MODS_PATH=$VAR_INTEGRATION_PATH/Mods
PHO_SCRIPTS_PATH=$VAR_INTEGRATION_PATH/Scripts

VAR_PENTAHO_PATH=$VAR_PDI_PATH/data-integration
VAR_PENTAHO_ERROR_LVL=Minimal                                                 # Basic, Detailed, Debug, Rowlevel, Error, Minimal, Nothing

VAR_TELEGRAM_TOKEN="517582275:AAEb1DMBTSP26HWKV_h_ElIAWquz8sAR8e8"
VAR_TELEGRAM_MESSAGE_URL="https://api.telegram.org/bot$VAR_TELEGRAM_TOKEN/sendMessage"
VAR_TELEGRAM_ATTACHMENT_URL="https://api.telegram.org/bot$VAR_TELEGRAM_TOKEN/sendDocument"

# www.heliohost.org/

# user: fusionpl
# pass: F2ktz29nhH

# db host: fusionpl.heliohost.org
# db user: fusionpl_ucabrera              fusionpl_andrei fusionpl_alvaro
# db pass: ucabreraPass                   IHatePhoenix_20 SoyUnLoco
# db: fusionpl_BET_DB